AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: |
  An example RESTful service

Resources:

  ExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.6
      Handler: index.handler
      Events:
        CreateCustomers:
          Type: Api
          Properties:
            Path: /customers
            Method: post
            RestApiId: !Ref Api
        Customer:
          Type: Api
          Properties:
            Path: /customers/{customer}
            Method: any
            RestApiId: !Ref Api
        DeleteCustomer:
          Type: Api
          Properties:
            Path: /customers/{customer}
            Method: delete
            RestApiId: !Ref Api
        Orders:
          Type: Api
          Properties:
            Path: /customers/{customer}/orders
            Method: get
            RestApiId: !Ref Api
      CodeUri: .

  AnotherFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.6
      Handler: another-handler.handler
      Events:
        ListCustomers:
          Type: Api
          Properties:
            Path: /customers
            Method: get
            RestApiId: !Ref Api
      CodeUri: .

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: "Prod"

  BasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: "adhoc_service"
      DomainName: "api.fsdpt.org"
      RestApiId: !Ref Api
      Stage: "Prod"
